### PR TITLE
Add Painting Studio wallpaper

### PR DESCRIPTION
**Pull request by BalanAlexandru**
- Added new wallpaper
- Updated readme file and uploaded gif screenshot to digital art section

### CODE REVIEW

**Comment by amrosolaiman** [comment]
Nice wallpaper!

**Comment by BalanAlexandru** [comment]
Hey @amrosolaiman there's a small problem with the wallpaper path, will fix it and push again

**Comment by BalanAlexandru** [comment]
Everything is tested and works fine now 😄 @amrosolaiman

**Comment by amrosolaiman** [comment]
> Everything is tested and works fine now 😄 @amrosolaiman

Very good @BalanAlexandru !

**Pull request merged**
